
```{r}
library(tidyverse)
library(ggridges)
library(reshape2)
library(wesanderson)
```

```{r}
theme_set(theme_classic()+
            theme(panel.grid.major.y=element_line(colour="grey90", size=0.5))+
            theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
            )
```

```{r}
fcw <- read.csv("fcw.csv", stringsAsFactors = FALSE)
summary(fcw)
```
```{r}
summary <- fcw %>%
  filter(CAMPAIGN_NUMBER != 500862) %>%
  group_by(campaign_year) %>%
  summarise(responder = n(),
            owner = sum(owner_flag),
            bn_owner = sum(ifelse(SALES_LOYALTY_STATUS != '',1,0)),
            bn_newtoF_owner = sum(ifelse(SALES_LOYALTY_STATUS=='NEW',1,0)),
            car_owner = sum(car_flag)/sum(owner_flag),
            truck_owner = sum(truck_flag)/sum(owner_flag),
            suv_owner = sum(suv_flag)/sum(owner_flag),
            mustang_owner = sum(mustang_flag)/sum(owner_flag),
            bnsr_total = sum(bnsr_cnt),
            busr_total = sum(busr_cnt),
            male = sum(male_ind,na.rm = TRUE)/sum(!is.na(male_ind)),
            female = (sum(!is.na(male_ind))-sum(male_ind,na.rm = TRUE))/sum(!is.na(male_ind)))

summary(summary)
```


```{r}
# Bar by Time
ggplot(summary, aes(x=factor(campaign_year), y=responder)) +
  geom_bar(stat="identity", width = 0.6, fill='steelblue', color="steelblue")  +
  ggtitle("Unique Responders") + xlab("Year") + ylab("Unique Responders")
```
```{r}
# Line chart by Time with data label
ggplot(summary, aes(x=factor(campaign_year), y=1-owner/responder, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(1-owner/responder,2)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0.7,NA)) +
  ggtitle("Conquest (non-owner) Mix Last 10 years") + xlab("Year") + ylab("Conquest Mix Last 10 years")
```

```{r}
year <- c("1", "2", "3+")
mix <- c(91, 6, 3)
visit <- data.frame(year, mix)

slices <- c(3, 6, 91) 
lbls <- c("3+", "2", "1")
pct <- round(slices/sum(slices)*100)
lbls <- paste(lbls, pct) # add percents to labels 
lbls <- paste(lbls,"%",sep="") # ad % to labels 
pie(slices,labels = lbls, col=rainbow(length(lbls)),
  	main="# of Year Responded")
```


```{r}
# Vehicle Segment Owned
summary2 <- summary %>%
  select(campaign_year, car_owner, truck_owner, suv_owner, mustang_owner) %>%
  gather(variable, value, -campaign_year)
```

```{r}
ggplot(summary2, aes(x = factor(campaign_year), y=value, group=variable, shape=variable, colour=variable)) + 
  geom_line() +
  geom_point() +
  theme(legend.justification=c(1,0.3), legend.position=c(1,0.3)) +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Vehicle Segment Owned") + xlab("Year") + ylab("Percent of Owner")
```

```{r}
# Line chart by Time with data label
ggplot(summary, aes(x=factor(campaign_year), y=bn_newtoF_owner/bn_owner, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(bn_newtoF_owner/bn_owner,2)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0.48, NA)) +
  ggtitle("New to F Mix") + xlab("Year") + ylab("")
```

```{r}
fcw.age <- fcw %>%
  filter(!is.na(individual_age) & individual_age>=18 & campaign_year<2018)

ggplot(fcw.age, aes(individual_age))+
  geom_density(aes(fill=factor(campaign_year)), alpha=0.8) + 
  labs(title="Density plot", 
       subtitle="City Mileage Grouped by Number of cylinders",
       caption="Source: mpg",
       x="City Mileage",
       fill="# Cylinders") +
  scale_fill_hue(c=80, l=80)
```
```{r}
ggplot(fcw.age, aes(x=factor(campaign_year), y=individual_age, fill=factor(campaign_year))) +
    geom_boxplot(alpha=0.4) +
    stat_summary(fun.y=mean, geom="point", shape=20, size=5, color="red", fill="red") +
    theme(legend.position="none") +
    scale_fill_brewer(palette="Set3") +
    ggtitle("Age Boxplot") + xlab("") + ylab("")

fcw.age %>%
  group_by(campaign_year) %>%
  summarize(med = median(individual_age))
```
```{r}
ggplot(fcw.age, aes(x = individual_age, y = factor(campaign_year), fill = factor(campaign_year))) +
  geom_density_ridges() +
  theme_ridges() +
  theme(legend.position = "none") +
  ggtitle("Age Density") + xlab("") + ylab("") +
  scale_fill_hue(c=80, l=80)
```
```{r}
summary.gender <- summary %>%
  select(campaign_year, male, female) %>%
  gather(variable, value, -campaign_year)

# Line chart by Time with data label
ggplot(data=summary.gender, aes(x=factor(campaign_year), y=value, fill=variable)) +
  geom_bar(stat="identity") +
  geom_text(position="stack", aes(label=paste(round(value,2)*100,'%',sep=""), hjust=0.5, vjust= 3), size=3) +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Gender Mix") + xlab("Year") + ylab("") +
  scale_fill_hue(c=80, l=80)
```
```{r}
summary.o <- fcw %>%
  group_by(campaign_year) %>%
  filter(owner_flag == 1 & campaign_year != 2018) %>%
  summarise(responder = n(),
            buy_new = sum(buy_new),
            buy_new_car = sum(buy_new_car),
            buy_new_truck = sum(buy_new_truck),
            buy_new_suv = sum(buy_new_suv),
            buy_new_mustang = sum(buy_new_mustang),
            buy_rate = sum(buy_new)/n()) %>%
  mutate(car = buy_new_car/buy_new,
         truck = buy_new_truck/buy_new,
         suv = buy_new_suv/buy_new,
         mustang = buy_new_mustang/buy_new)

summary(summary.o)
```
```{r}
# Line chart by Time with data label
ggplot(summary.o, aes(x=factor(campaign_year), y=buy_rate, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(buy_rate,3)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.08)) +
  ggtitle("Buy Rate After Event (12-month)") + xlab("Year") + ylab("")
```
```{r}
summary.o2 <- summary.o %>%
  select(campaign_year, car, truck, suv) %>%
  gather(variable, value, -campaign_year)
```

```{r}
ggplot(data=summary.o2, aes(x=factor(campaign_year), y=value, fill=variable)) +
  geom_bar(stat="identity") +
  geom_text(position="stack", aes(label=paste(round(value,3)*100,'%',sep=""), hjust=0.5, vjust= 3), size=3) +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Purchase Vehicle Segment Mix") + xlab("Year") + ylab("") +
  scale_fill_hue(c=80, l=80)
```
```{r}
# Line chart by Time with data label
ggplot(summary.o, aes(x=factor(campaign_year), y=mustang, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(mustang,3)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.16)) +
  ggtitle("Purchase Mustang Mix") + xlab("Year") + ylab("")
```

```{r}
summary.c <- fcw %>%
  group_by(campaign_year) %>%
  filter(owner_flag == 0 & campaign_year !=2018) %>%
  summarise(responder = n(),
            buy_new = sum(buy_new),
            buy_new_car = sum(buy_new_car),
            buy_new_truck = sum(buy_new_truck),
            buy_new_suv = sum(buy_new_suv),
            buy_new_mustang = sum(buy_new_mustang),
            buy_rate = sum(buy_new)/n()) %>%
  mutate(car = buy_new_car/buy_new,
         truck = buy_new_truck/buy_new,
         suv = buy_new_suv/buy_new,
         mustang = buy_new_mustang/buy_new)

summary(summary.c)
```

```{r}
# Line chart by Time with data label
ggplot(summary.c, aes(x=factor(campaign_year), y=buy_rate, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(buy_rate,3)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.009)) +
  ggtitle("Buy Rate After Event (12-month)") + xlab("Year") + ylab("")
```

```{r}
summary.c2 <- summary.c %>%
  select(campaign_year, car, truck, suv) %>%
  gather(variable, value, -campaign_year)
```

```{r}
ggplot(data=summary.c2, aes(x=factor(campaign_year), y=value, fill=variable)) +
  geom_bar(stat="identity") +
  geom_text(position="stack", aes(label=paste(round(value,3)*100,'%',sep=""), hjust=0.5, vjust= 3), size=3) +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Purchase Vehicle Segment Mix") + xlab("Year") + ylab("") +
  scale_fill_hue(c=80, l=80)
```

```{r}
# Line chart by Time with data label
ggplot(summary.c, aes(x=factor(campaign_year), y=mustang, group =1)) +
  geom_line(color='steelblue') +
  geom_point() +
  geom_text(aes(label=paste(round(mustang,3)*100,'%',sep="")), vjust=2) +
  scale_y_continuous(labels = scales::percent, limits = c(0, 0.1)) +
  ggtitle("Purchase Mustang Mix") + xlab("Year") + ylab("")
```
```{r}
summary.c <- summary.c %>% mutate(resp_type='Conq')
summary.o <- summary.o %>% mutate(resp_type='Owner')
summary.co <- rbind(summary.c, summary.o)
```

```{r}
ggplot(data=summary.co, aes(x=factor(campaign_year), y=buy_new, fill=factor(resp_type))) +
  geom_bar(stat="identity", position=position_dodge()) +
  geom_text(position = position_dodge(width = 1), aes(label = buy_new, hjust=0.5, vjust=2), size=3) +
  ggtitle("Purchases after Events") + xlab("Year") + ylab("") +
  guides(fill=guide_legend(title="Resp Type")) +
  scale_fill_hue(c=80, l=80)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).